apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-c7i-test
  labels:
    app: nginx-c7i-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-c7i-test
  template:
    metadata:
      labels:
        app: nginx-c7i-test
    spec:
      nodeSelector:
        workload-type: web
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values: ["c7i.xlarge"]
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 750m
            memory: 768Mi
          limits:
            cpu: 1500m
            memory: 1.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-c7i-test-svc
spec:
  selector:
    app: nginx-c7i-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
